### ISSUE TITLE
Encoder.Instance.Encode can not use in multithreading？

### ISSUE THREAD

**Issue by iamnewaplayer** [roy-t/SuperCompressedDotNet#2]
how can i use it in multithreading?
can not new Encoder()

**Comment by roy-t** [comment]
The Encoder instance already uses 8 threads to encode a single image (see: https://github.com/roy-t/SuperCompressed/blob/main/src/SuperCompressed.Native/Encoder.cpp#L67). So running multiple encoders at once usually doesn't save much time. Since the encoder interacts with native code having only one instance makes it easier for you as a user to not have to worry about clean-up :).
